const express=require('express');
const path=require('path');
const fs=require('fs');
const app=express();
const PORT=process.env.PORT||10000;
const ROOT=path.join(__dirname,'ЭТАЛОН-01','MMW-COMPANY');
const HOME=path.join(ROOT,'index.html');
if(!fs.existsSync(HOME)) throw new Error('MMW-COMPANY ETALON-01 home page is missing');
app.disable('x-powered-by');
app.get('/health',(req,res)=>res.json({status:'ok',app:'MMW-COMPANY',source:'MMW-ORDER-FACTORY/ЭТАЛОН-01/MMW-COMPANY'}));
app.use(express.static(ROOT));
app.use((req,res)=>res.sendFile(HOME));
app.listen(PORT,'0.0.0.0',()=>console.log(`MMW-COMPANY ETALON-01 listening on ${PORT}`));
