const express=require('express');
const path=require('path');
const fs=require('fs');
const app=express();
const PORT=process.env.PORT||10000;
const ROOT=path.join(__dirname,'MMW-COMPANY','2 — WORKING');
const PUBLIC=path.join(ROOT,'public');
const HOME=path.join(PUBLIC,'index.html');
if(!fs.existsSync(HOME)) throw new Error('MMW-ORDER START working home page is missing');
app.disable('x-powered-by');
app.get('/health',(req,res)=>res.json({status:'ok',app:'MMW-ORDER',source:'MMW-ORDER-FACTORY/MMW-COMPANY/2 — WORKING/START baseline'}));
app.use(express.static(PUBLIC));
app.use((req,res)=>res.sendFile(HOME));
app.listen(PORT,'0.0.0.0',()=>console.log(`MMW-ORDER START listening on ${PORT}`));
