const express = require('express');
const os = require('os');
const app = express();
const port = process.env.PORT || 10000;
app.get('/api/server-info', (_req,res)=>res.json({serverTime:new Date().toISOString(),platform:process.platform,node:process.version,hostname:os.hostname()}));
app.get('/', (_req, res) => {
  res.type('html').send(`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MMW DEVICE CONTROL</title><style>body{font-family:system-ui;margin:0;background:#07110d;color:#eef5f2}main{max-width:760px;margin:auto;padding:24px}section{background:#0d1c15;border:1px solid #536b5e;border-radius:18px;padding:18px;margin:12px 0}dt{opacity:.65;margin-top:9px}dd{margin:2px 0;font-size:17px}button{padding:11px 15px;border:0;border-radius:10px;font-weight:700}</style></head><body><main><h1>MMW DEVICE CONTROL</h1><section><b>ONLINE</b><p>Показываем информацию, которую Android разрешает веб-приложению получить.</p></section><section><dl id="info"></dl></section><button onclick="location.reload()">Обновить</button></main><script>const n=navigator,s=screen,c=navigator.connection||{};const d={'Платформа':n.platform,'Браузер':n.userAgent,'Язык':n.language,'Онлайн':n.onLine?'Да':'Нет','CPU (логические ядра)':n.hardwareConcurrency||'н/д','RAM браузера':n.deviceMemory?(n.deviceMemory+' GB'):'н/д','Экран':s.width+' × '+s.height,'Плотность':devicePixelRatio,'Ориентация':s.orientation?.type||'н/д','Сеть':c.effectiveType||'н/д','Часовой пояс':Intl.DateTimeFormat().resolvedOptions().timeZone};document.querySelector('#info').innerHTML=Object.entries(d).map(([k,v])=>'<dt>'+k+'</dt><dd>'+String(v).replaceAll('&','&amp;').replaceAll('<','&lt;')+'</dd>').join('');</script></body></html>`);
});
app.listen(port, '0.0.0.0', () => console.log(`MMW DEVICE CONTROL listening on ${port}`));
