const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const root=path.join(__dirname,"public"),dataDir=path.join(__dirname,"data"),ordersFile=path.join(dataDir,"orders.json"),port=process.env.PORT||10000;
if(!fs.existsSync(dataDir))fs.mkdirSync(dataDir,{recursive:true});
if(!fs.existsSync(ordersFile))fs.writeFileSync(ordersFile,"[]","utf8");
let writeQueue=Promise.resolve();
function readOrders(){try{return JSON.parse(fs.readFileSync(ordersFile,"utf8")||"[]")}catch{return[]}}
function saveOrders(items){writeQueue=writeQueue.then(()=>fs.promises.writeFile(ordersFile,JSON.stringify(items,null,2),"utf8"));return writeQueue}
function cleanPhone(v){return String(v||"").replace(/\D/g,"").slice(-15)}
function hashCode(code,salt){return crypto.scryptSync(String(code),salt,32).toString("hex")}
function makeCode(){return String(crypto.randomInt(10000,100000))}
function json(res,status,data){const body=JSON.stringify(data);res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"});res.end(body)}
function body(req){return new Promise((resolve,reject)=>{let s="";req.on("data",c=>{s+=c;if(s.length>200000)reject(new Error("payload too large"))});req.on("end",()=>{try{resolve(JSON.parse(s||"{}"))}catch{reject(new Error("invalid json"))}});req.on("error",reject)})}
function safeOrder(o){return{orderNumber:o.orderNumber,status:o.status,name:o.name,phoneMasked:o.phoneMasked,items:o.items.map(x=>({name:x.name,price:x.price,unit:x.unit})),total:o.total,comment:o.comment,createdAt:o.createdAt}}
async function handleApi(req,res,u){
 if(req.method==="POST"&&u==="/api/orders"){try{const b=await body(req),name=String(b.name||"").trim(),phone=cleanPhone(b.phone),email=String(b.email||"").trim(),comment=String(b.comment||"").trim(),items=Array.isArray(b.items)?b.items.map(x=>({id:String(x.id||""),name:String(x.name||"").slice(0,160),price:Number(x.price)||0,unit:String(x.unit||"").slice(0,50)})).slice(0,30):[];if(name.length<2||phone.length<7||!items.length)return json(res,400,{error:"Нужны имя, корректный телефон и хотя бы одна позиция."});const orders=readOrders(),year=new Date().getFullYear(),n=String(orders.length+1).padStart(6,"0"),orderNumber="MMW-"+year+"-"+n,code=makeCode(),salt=crypto.randomBytes(16).toString("hex"),total=items.reduce((s,x)=>s+x.price,0),order={orderNumber,name,phone,phoneMasked:"+"+phone.slice(0,3)+"••••"+phone.slice(-2),email,comment,items,total,status:"NEW",createdAt:new Date().toISOString(),accessSalt:salt,accessHash:hashCode(code,salt)};orders.push(order);await saveOrders(orders);return json(res,201,{orderNumber,accessCode:code,status:"NEW",total})}catch(e){return json(res,400,{error:e.message||"Ошибка заявки"})}}
 if(req.method==="POST"&&u==="/api/orders/access"){try{const b=await body(req),phone=cleanPhone(b.phone),code=String(b.code||"").replace(/\D/g,"");if(phone.length<7||!/^\d{5}$/.test(code))return json(res,400,{error:"Введите телефон и код из 5 цифр."});const order=readOrders().find(o=>o.phone===phone&&o.accessHash===hashCode(code,o.accessSalt));if(!order)return json(res,401,{error:"Заявка не найдена или код неверен."});return json(res,200,{order:safeOrder(order)})}catch(e){return json(res,400,{error:"Ошибка проверки доступа"})}}
 return false;
}
const server=http.createServer(async(req,res)=>{const u=(req.url||"/").split("?")[0];if(u.startsWith("/api/")){const done=await handleApi(req,res,u);if(done!==false)return}let clean=decodeURIComponent(u);if(clean==="/"||!clean.includes("."))clean="/index.html";let f=path.join(root,clean.replace(/^\//,""));if(!f.startsWith(root)){res.writeHead(403);return res.end("Forbidden")}fs.readFile(f,(e,d)=>{if(e){res.writeHead(404,{"Content-Type":"text/plain; charset=utf-8"});return res.end("Not found")}const ext=path.extname(f),types={".html":"text/html; charset=utf-8",".css":"text/css",".js":"text/javascript",".svg":"image/svg+xml",".json":"application/json"};res.writeHead(200,{"Content-Type":types[ext]||"application/octet-stream","Cache-Control":"public,max-age=60","X-Content-Type-Options":"nosniff"});res.end(d)})});
server.listen(port,"0.0.0.0",()=>console.log("MMW-COMPANY on "+port));