const CATALOG_VERSION="2026-10-03";
const projectNames={
 "aladin-residence":"ALADIN RESIDENCE","nexus-work":"NEXUS WORK","nexus-logistics":"NEXUS LOGISTICS",
 "carpathia-eco-lodge":"CARPATHIA ECO LODGE","agrohub":"AGROHUB","energy-park":"ENERGY PARK"
};
const items=[
 {id:"project-audit",category:"Развитие проектов",name:"Предпроектный аудит",price:15000,from:false,unit:"проект",description:"Первичная проверка возможности: исходные данные, рынок, площадка и ключевые вопросы реализации."},
 {id:"project-concept",category:"Развитие проектов",name:"PROJECT CONCEPT",price:49000,from:false,unit:"проект",description:"Разработка и структурирование концепции проекта с продуктовой логикой и планом дальнейшей проверки."},
 {id:"business-project",category:"Развитие проектов",name:"BUSINESS PROJECT",price:119000,from:false,unit:"проект",description:"Бизнес-модель, финансовый контур, план запуска и рабочая структура проекта."},
 {id:"investment-project",category:"Инвестиции",name:"INVESTMENT PROJECT",price:169000,from:false,unit:"проект",description:"Инвестиционная упаковка, экономика, структура сделки и материалы для работы с капиталом."},
 {id:"business-system",category:"Управление",name:"BUSINESS SYSTEM",price:249000,from:false,unit:"проект",description:"Проектирование управленческой и операционной системы: процессы, роли, контроль и KPI."},
 {id:"business-restart",category:"Развитие проектов",name:"BUSINESS RESTART",price:99000,from:false,unit:"проект",description:"Диагностика действующего бизнеса, новая модель, план изменений и приоритеты."},
 {id:"business-investor",category:"Инвестиции",name:"BUSINESS + INVESTOR",price:229000,from:false,unit:"проект",description:"Бизнес-проект и комплексная подготовка к работе с инвестором."},
 {id:"custom-business-project",category:"Развитие проектов",name:"CUSTOM BUSINESS PROJECT",price:299000,from:true,unit:"проект",description:"Индивидуальный комплексный проект под нестандартную задачу."},
 {id:"large-scale",category:"Развитие проектов",name:"LARGE SCALE",price:499000,from:true,unit:"проект",description:"Крупный комплексный проект с расширенным сопровождением."},
 {id:"estimate",category:"Отдельные услуги",name:"Расширенная смета",price:12000,from:false,unit:"задача",description:"Детализированный расчёт стоимости по согласованным исходным данным."},
 {id:"site-survey",category:"Отдельные услуги",name:"Выезд / обследование объекта",price:8000,from:false,unit:"выезд",description:"Первичное обследование площадки или объекта и фиксация исходных данных."},
 {id:"docs",category:"Отдельные услуги",name:"Дополнительный комплект документов",price:7500,from:false,unit:"комплект",description:"Подготовка дополнительного набора рабочих форм и документов."},
 {id:"management",category:"Отдельные услуги",name:"Проектное сопровождение",price:18000,from:false,unit:"месяц",description:"Координация задач, участников, сроков и контрольных точек проекта."},
 {id:"urgent",category:"Отдельные услуги",name:"Срочное оформление",price:10000,from:false,unit:"задача",description:"Приоритетная подготовка согласованного объёма работ."},
  {id:"project-urban-residential",category:"Недвижимость",name:"URBAN RESIDENTIAL",price:189000,from:true,unit:"проект",description:"Концепция жилого проекта: продукт, площадка, спрос, экономика и сценарий реализации."},
 {id:"project-commercial-center",category:"Недвижимость",name:"COMMERCIAL CENTER",price:219000,from:true,unit:"проект",description:"Коммерческий объект с торговыми, сервисными и общественными функциями."},
 {id:"project-industrial-park",category:"Промышленность",name:"INDUSTRIAL PARK",price:399000,from:true,unit:"проект",description:"Промышленная площадка для резидентов, инженерной инфраструктуры и поэтапного развития."},
 {id:"project-food-plant",category:"Производство",name:"FOOD PRODUCTION",price:299000,from:true,unit:"проект",description:"Концепция пищевого производства от сырья и технологии до рынка и операционной модели."},
 {id:"project-light-manufacturing",category:"Производство",name:"LIGHT MANUFACTURING",price:269000,from:true,unit:"проект",description:"Производственный проект для малого и среднего бизнеса с возможностью масштабирования."},
 {id:"project-cold-chain",category:"Логистика",name:"COLD CHAIN",price:249000,from:true,unit:"проект",description:"Инфраструктура хранения и доставки продукции с температурным режимом."},
 {id:"project-distribution-center",category:"Логистика",name:"DISTRIBUTION CENTER",price:349000,from:true,unit:"проект",description:"Распределительный центр для торговых сетей, производителей и e-commerce."},
 {id:"project-data-center",category:"Цифровая инфраструктура",name:"DATA CENTER",price:599000,from:true,unit:"проект",description:"Концепция инфраструктурного объекта для размещения цифровых мощностей и сервисов."},
 {id:"project-solar-generation",category:"Энергетика",name:"SOLAR GENERATION",price:299000,from:true,unit:"проект",description:"Проект солнечной генерации с площадкой, подключением, экономикой и моделью эксплуатации."},
 {id:"project-energy-storage",category:"Энергетика",name:"ENERGY STORAGE",price:349000,from:true,unit:"проект",description:"Инфраструктура накопления энергии для бизнеса, промышленности или энергосистемы."},
 {id:"project-biogas",category:"Энергетика",name:"BIOGAS & ENERGY",price:329000,from:true,unit:"проект",description:"Проект энергетической утилизации органического сырья с оценкой ресурса и экономики."},
 {id:"project-water-infrastructure",category:"Инфраструктура",name:"WATER INFRASTRUCTURE",price:279000,from:true,unit:"проект",description:"Инфраструктурный проект водоснабжения, подготовки воды или технических сетей."},
 {id:"project-waste-recycling",category:"Экология",name:"WASTE & RECYCLING",price:249000,from:true,unit:"проект",description:"Проект сбора, сортировки, переработки и коммерческого использования вторичных ресурсов."},
 {id:"project-healthcare-center",category:"Здравоохранение",name:"HEALTHCARE CENTER",price:229000,from:true,unit:"проект",description:"Медицинский объект с продуктовой моделью, сервисами, площадкой и операционной логикой."},
 {id:"project-education-campus",category:"Образование",name:"EDUCATION CAMPUS",price:249000,from:true,unit:"проект",description:"Образовательный комплекс с учебными, сервисными и общественными функциями."},
 {id:"project-hotel",category:"Гостеприимство",name:"HOTEL PROJECT",price:299000,from:true,unit:"проект",description:"Гостиничный проект от позиционирования и продукта до операционной модели и экономики."},
 {id:"project-wellness",category:"Гостеприимство",name:"WELLNESS RETREAT",price:279000,from:true,unit:"проект",description:"Комплекс отдыха и восстановления с программой услуг, размещением и экономической моделью."},
 {id:"project-agro-processing",category:"Агробизнес",name:"AGRO PROCESSING",price:299000,from:true,unit:"проект",description:"Переработка аграрного сырья с расчётом продукта, рынка, технологии и логистики."},
 {id:"project-agro-storage",category:"Агробизнес",name:"AGRO STORAGE",price:229000,from:true,unit:"проект",description:"Современная инфраструктура хранения урожая с управлением сезонностью и качеством."},
 {id:"project-retail-park",category:"Торговая инфраструктура",name:"RETAIL PARK",price:269000,from:true,unit:"проект",description:"Торгово-сервисный парк для нескольких операторов с поэтапным развитием."},
 {id:"project-business-campus",category:"Деловая инфраструктура",name:"BUSINESS CAMPUS",price:319000,from:true,unit:"проект",description:"Многофункциональная деловая среда для компаний, сервисов, обучения и мероприятий."},
 {id:"project-mobility-hub",category:"Транспорт",name:"MOBILITY HUB",price:279000,from:true,unit:"проект",description:"Транспортно-сервисный узел для городской, региональной или корпоративной мобильности."},
 {id:"project-ev-charging",category:"Транспорт",name:"EV CHARGING NETWORK",price:199000,from:true,unit:"проект",description:"Сеть зарядной инфраструктуры с подбором локаций, мощностей и модели эксплуатации."},
 {id:"project-sports-complex",category:"Спорт",name:"SPORTS COMPLEX",price:249000,from:true,unit:"проект",description:"Спортивный объект с программой помещений, клиентскими сценариями и операционной моделью."},
 {id:"project-corporate-campus",category:"Корпоративная инфраструктура",name:"CORPORATE CAMPUS",price:449000,from:true,unit:"проект",description:"Крупный корпоративный комплекс: рабочая среда, сервисы, обучение, инфраструктура и этапность реализации."},...Object.entries(projectNames).map(([id,name])=>({id:"start-"+id,category:"Проекты MMW-COMPANY",name:name+" · старт проекта",price:15000,from:true,unit:"проект",description:"Стартовая предпроектная оценка конкретного проекта MMW-COMPANY. Финальный объём и бюджет определяются после проверки исходных данных."}))
];
module.exports={CATALOG_VERSION,items,projectNames};
